window.DEFAULT_ROUTINE = {
  eyebrow: "Protocolo biomecánico",
  title: "Rutina de",
  titleAccent: "piernas",
  titleSuffix: "para corredores",
  featuring: "Silvia Adriana Gonzalez",
  client: "Lalo",
  lead:
    "Cinco bloques de fuerza diseñados para mejorar economía de carrera, estabilidad unipodal y resiliencia ante impacto — sin hipertrofia innecesaria.",
  metaBlocks: "5",
  metaMinutes: "~45",
  metaFrequency: "2×",
  exercises: [
    {
      id: "squat",
      shortLabel: "Sentadilla",
      tag: "Fuerza",
      badge: "01 · Base de fuerza máxima",
      title: "Sentadilla libre",
      titleEm: "(Back Squat)",
      intro:
        "El estándar para reclutar unidades motoras, aumentar la rigidez tendinosa y mejorar la capacidad de absorber impacto en cada zancada. Aquí no buscamos volumen muscular: buscamos fuerza reactiva transferible a la carrera.",
      doseValue: "3–4 × 5–6",
      doseMeta: "RPE 7–8 · Descanso 2–3 min",
      purpose:
        "Desarrolla fuerza reactiva y potencia de extensión triple (cadera, rodilla y tobillo). Al elevar la tendon stiffness, el Aquiles y el cuádriceps almacenan y liberan energía elástica con más eficiencia en el contacto pie–suelo.",
      bullets: [
        "RFD: enseña al sistema nervioso a reclutar fibras rápido.",
        "Resistencia a la deformación: reduce el colapso excesivo de rodilla.",
        "Economía de carrera: menos tiempo de contacto y menor coste de O₂.",
      ],
      agonists: "Cuádriceps (recto femoral, vastos), Glúteo mayor",
      synergists: "Erectores espinales, Aductor mayor, Isquiotibiales, Sóleo y gastrocnemio",
      steps: [
        "Setup — Barra sobre trapecios. Pies al ancho de hombros, rotación externa 15–30°. Activa el trípode plantar.",
        "Brace — Inhala 360° hacia el abdomen y estabiliza la columna antes de descender.",
        "Excéntrica — Flexiona cadera y rodilla a la vez hasta romper la paralela si la movilidad lo permite.",
        "Concéntrica — Empuja el suelo con intención. Pecho alto, rodillas sobre la línea de los pies.",
      ],
      mistakes: [
        "Valgo dinámico: la rodilla se hunde hacia dentro.",
        "Butt wink: la pelvis se mete en profundidad.",
        "Talones que se levantan: sobrecarga patelofemoral.",
      ],
      benefit:
        "Mejora la economía de carrera, retrasa la fatiga neuromuscular y ayuda a prevenir tendinopatía rotuliana y runner’s knee.",
      image: "images/squat.png",
      parts: [],
    },
    {
      id: "rdl",
      shortLabel: "Single-Leg RDL",
      tag: "Unipodal",
      badge: "02 · Cadena posterior unipodal",
      title: "Single-Leg RDL",
      titleEm: "(Peso muerto rumano)",
      intro:
        "Fortalece isquiotibiales y glúteos en un patrón de una sola pierna que replica la biomecánica del ciclo de zancada.",
      doseValue: "3 × 8–10 /pierna",
      doseMeta: "RPE 7 · Descanso 90 s",
      purpose:
        "Entrena la bisagra de cadera en una pierna mientras glúteo medio y tobillo evitan la rotación pélvica y el colapso del arco plantar.",
      bullets: [
        "Sincronización posterior de isquiotibiales en longitud funcional.",
        "Control anti-rotacional del core profundo.",
        "Simetría izquierda–derecha que la sentadilla bilateral puede ocultar.",
      ],
      agonists: "Isquiotibiales, Glúteo mayor",
      synergists: "Glúteo medio y menor, Tibial posterior y peroneos, Multífidos y cuadrado lumbar",
      steps: [
        "Posición — Apoyo en una pierna con microflexión 10–15°. Pierna libre larga detrás.",
        "Bisagra — Empuja la cadera hacia atrás. Torso y pierna libre bajan en T.",
        "Pelvis nivelada — Crestas ilíacas mirando al suelo; no abras la cadera libre.",
        "Extensión — Empuja el talón de apoyo y cierra con el glúteo hasta la vertical.",
      ],
      mistakes: [
        "Flexionar la columna en vez de bisagrar desde la cadera.",
        "Perder el trípode plantar o dejar caer el arco interno.",
        "Rotar en exceso la cadera de la pierna elevada.",
      ],
      benefit:
        "Reduce el riesgo de distensiones de isquiotibiales y mejora la estabilidad pélvica (Trendelenburg).",
      image: "images/rdl.png",
      parts: [],
    },
    {
      id: "combo",
      shortLabel: "Búlgara + Step-Up",
      tag: "Potencia",
      badge: "03 · Dúo unipodal de potencia",
      title: "Búlgara + Step-Up",
      titleEm: "",
      intro:
        "Combo obligatorio: la búlgara construye fuerza de desaceleración; el step-up con ataque de rodilla transfiere esa fuerza a propulsión y cuestas.",
      doseValue: "3 × 8 + 8 /pierna",
      doseMeta: "Biserie · Descanso 2 min",
      purpose: "",
      bullets: [],
      agonists: "",
      synergists: "",
      steps: [],
      mistakes: [
        "Búlgara: inclinarte en exceso o levantar el talón delantero.",
        "Step-up: impulsarte con el pie inferior; la carga debe vivir arriba.",
      ],
      benefit:
        "Ayuda a prevenir ITBS y condromalacia rotuliana, y aporta potencia para desniveles.",
      image: "",
      parts: [
        {
          code: "3A",
          title: "Sentadilla búlgara",
          pill: "Fuerza unipodal profunda",
          text: "Sobrecarga cuádriceps y glúteos en rango profundo mientras estira los flexores de la pierna trasera.",
          muscles: "Cuádriceps, glúteo mayor, glúteo medio, aductor mayor",
          steps: [
            "Empeine trasero sobre un banco a altura de rodilla.",
            "Pie delantero a 60–80 cm del banco; torso erguido.",
            "Desciende en vertical hasta que la rodilla trasera casi toque el suelo.",
            "Rodilla delantera alineada con el 2º dedo; empuja el suelo para volver.",
          ],
          image: "images/bulgarian.png",
        },
        {
          code: "3B",
          title: "Step-up explosivo con knee drive",
          pill: "Propulsión y ataque de zancada",
          text: "Replica el impulso en pendiente y el knee drive: extensión rápida + rodilla contralateral a 90°.",
          muscles: "Glúteo mayor, psoas/ilíaco contralateral, sóleo",
          steps: [
            "Pie completo sobre un cajón (~90° de flexión).",
            "Empuja solo con la pierna de arriba — sin impulsarte desde el suelo.",
            "Arriba: triple extensión + rodilla libre hacia el pecho a 90°.",
            "Baja en 3 segundos con control excéntrico.",
          ],
          image: "images/stepup.png",
        },
      ],
    },
    {
      id: "copenhagen",
      shortLabel: "Copenhagen",
      tag: "Core",
      badge: "04 · Estabilidad aductora",
      title: "Plancha Copenhagen",
      titleEm: "(Adductor plank)",
      intro:
        "El estándar para salud de aductores, estabilidad pélvica lateral y transferencia de fuerza en el plano frontal.",
      doseValue: "3 × 20–30 s /lado",
      doseMeta: "Isométrico · Descanso 60 s",
      purpose:
        "El aductor mayor actúa como estabilizador pélvico. La Copenhagen genera co-contracción entre ingle y core lateral.",
      bullets: [
        "Balance aductor/abductor con el glúteo medio.",
        "Estabilidad del anillo pélvico frente a impactos repetitivos.",
      ],
      agonists: "Aductor mayor, largo y corto, Grácil y pectíneo",
      synergists: "Oblicuos, Cuadrado lumbar, Glúteo medio contralateral",
      steps: [
        "Lateral — Antebrazo a 90° respecto al hombro.",
        "Apoyo — Rodilla (principiante) o tobillo (avanzado) de la pierna superior en el banco.",
        "Elevación — Sube la cadera en línea recta cabeza–pies.",
        "Aducción — Pierna inferior elevada bajo el banco; respira fluido.",
      ],
      mistakes: [
        "Dejar caer la cadera por fatiga.",
        "Rotar el pecho hacia el suelo.",
        "Pasar a palanca de tobillo antes de dominar la de rodilla.",
      ],
      benefit: "Reduce pubalgia y sobrecargas de ingle; estabiliza la cadera en terreno irregular.",
      image: "images/copenhagen.png",
      parts: [],
    },
    {
      id: "ankle",
      shortLabel: "Tobillo",
      tag: "Impacto",
      badge: "05 · Complejo antero-posterior de tobillo",
      title: "Tobillo & pantorrilla",
      titleEm: "",
      intro:
        "Trabajo focal del sóleo (propulsión) y del tibial anterior (freno del pie en el heel strike).",
      doseValue: "3–4 × 12–15",
      doseMeta: "Excéntrica 3 s · Descanso 60 s",
      purpose: "",
      bullets: [],
      agonists: "",
      synergists: "",
      steps: [],
      mistakes: [
        "Rebotar abajo en el sóleo y perder tensión.",
        "Rotar el tobillo en vez de moverlo en plano sagital.",
      ],
      benefit: "Útil contra periostitis tibial, tendinopatía de Aquiles, fascitis plantar y fracturas por estrés.",
      image: "",
      parts: [
        {
          code: "5A",
          title: "Elevación de talón sentado",
          pill: "Sóleo",
          text: "Con rodilla a 90°, el sóleo asume casi toda la carga de plantarflexión (6–8× peso corporal al correr).",
          muscles: "Sóleo",
          steps: [
            "Rodillas a 90° y metatarsos sobre un bloque.",
            "Carga sobre los muslos, cerca de las rodillas.",
            "Baja el talón al máximo en 3 s.",
            "Empuja por el metatarso y pausa 1 s arriba.",
          ],
          image: "images/soleus.png",
        },
        {
          code: "5B",
          title: "Eleva-puntas con pesa rusa",
          pill: "Tibial anterior",
          text: "El tibial anterior frena la caída del pie en el contacto inicial. Si está débil, el impacto viaja a la tibia.",
          muscles: "Tibial anterior",
          steps: [
            "Siéntate en banco alto con piernas colgando.",
            "Engancha pesa rusa ligera (4–8 kg) o banda en el empeine.",
            "Dorsiflexiona llevando la punta hacia la espinilla.",
            "Pausa arriba y baja en 3 s.",
          ],
          image: "images/tibialis.png",
        },
      ],
    },
  ],
};

window.EMPTY_EXERCISE = () => ({
  id: `ex-${Date.now()}-${Math.floor(Math.random() * 999)}`,
  shortLabel: "Nuevo",
  tag: "Fuerza",
  badge: "Nuevo bloque",
  title: "Nombre del ejercicio",
  titleEm: "",
  intro: "",
  doseValue: "3 × 8–10",
  doseMeta: "Descanso 90 s",
  purpose: "",
  bullets: [],
  agonists: "",
  synergists: "",
  steps: ["", "", ""],
  mistakes: [""],
  benefit: "",
  image: "",
  parts: [],
});
